env_factories:
  factories:
    - factory: python_di.inject.context_builder.factory_ctx.FactoryCtx
      lazy: False
    - factory: python_di.inject.reflectable_ctx.ReflectableCtx
      lazy: False
scanner:
  src_file: '/Users/hayde/IdeaProjects/drools/python_di/test/reflection_tests/__init__.py'
  num_up: 0
