profiles:
  active_profiles:
    test:
      profile_name: test
      priority: -100
    prod:
      profile_name: prod
      priority: 100
    main_profile:
      profile_name: main_profile
      priority: 1000000
